### ISSUE TITLE
Send FQDN as hostname to Riemann downstream

### ISSUE THREAD

**Issue by heretogo** [sandfox/riemann-nodejs-client#10]
Is it possible to configure the client to use the FQDN in the :host field?

**Comment by sandfox** [comment]
As far as I remember the client can only see the `os.hostname()`, and there's no built in way to easily work out the FQDN from within the client. You can overwrite the `host` that gets sent by setting it in your event, so as long as you can work it out in your code then it's possible to set it:

```js
client.send(client.Event({
  host: 'server.clust.your.domain.com'
  service: 'buffet_plates',
  metric:  252.2,
  tags:    ['nonblocking']
}));
```

**Comment by heretogo** [comment]
That's helpful. Thanks.
